DROP TABLE "GAB_4048_CONFCHK" IN DICTIONARY;
CREATE TABLE "GAB_4048_CONFCHK"("PURCHASE_ORDER" CHAR(7),"CONF" CHAR(1),"USER" CHAR(8),"DATE_CONF" DATE);
CREATE INDEX "GAB_4048_CONFCHKCHK00" ON "GAB_4048_CONFCHK"("PURCHASE_ORDER" ASC);